### PR TITLE
Incorporate @trilnick suggestions for formatPLSS

### PR DESCRIPTION
**Pull request by brownag**
stub fixes for #33 -- still could incorporate some checks on resulting PLSS string length. Are they always supposed to be 25 characters? Are there cases where they might not be? Basically any character input is currently "allowed"

### CODE REVIEW

**Comment by trilnick** [comment]
I was also thinking about some check for string length in the function. In my case (the PUR data in California), there are no q and qq codes, which makes the string 21 characters long. I was going to suggest a check like this, but realized there might be many end-cases, some of which I am not aware of.

**Comment by brownag** [comment]
Thanks, @trilnick! Yes, when the quarters and quarter-quarter sections are not specified the string is 4 characters shorter. 
I think we can cross-check data-availability and expected number of characters. A bit more intelligent than my current use of `complete.cases`

**Comment by trilnick** [comment]
It can be tricky. I can think of several cases:
1) Missing both q and qq: nchar(string) = 21
2)Having q and missing qq: nchar(string) = 23
3) Having qq and missing q: should return an error or result for missing q as well with a warning.
4) Having both q and qq: nchar(string) = 25
5) If I read it correctly, when the type is PB, the 'A' is dropped, probably making the string shorter.
6) Are all the meridian codes of the same length?
7) will the website take even shorter strings? Like, just the township, and return all the points in this 6X6 miles square? I've tried to find the documentation for this service on the website but got lost.

Now, running all these (and potentially more) end cases  in the for loop for every line in p hurts my feelings a little bit. With a full list of end cases, perhaps a separate inner .function can be devised for the testing.

**Comment by brownag** [comment]
I fiddled around with this a bit last night and made some notes. No more time to mess with this today, but want to leave it out there for others to test.

``` r
library(sp)
library(sharpshootR)

d <- data.frame(
  id = 1:3,
  qq = c('SW', NA, NA),
  q = c('NE', NA, NA),
  s = c(17, NA, 30),
  t = c('T36N', 'T35N', 'T35N'),
  r = c('R29W', 'R28W', 'R28W'),
  type = 'SN',
  m = 'MT20',
  stringsAsFactors = FALSE
)
  
# get centroids for PLSS extents
res1 <- PLSS2LL(data.frame(id = 1:3, plssid = formatPLSS(d)))
res1
#>   id                    plssid      lat       lon
#> 1  1 MT200360N0290W0SN170ASWNE 48.88590 -115.3768
#> 2  2           MT200350N0280W0 48.78940 -115.2165
#> 3  3     MT200350N0280W0SN300A 48.76717 -115.2712

# returns quarter-quarter section at whatever centroid was returned
res2 <- LL2PLSS(res1$lon, res1$lat)
res2
#> $plss
#> [1] "MT200360N0290W0SN170ASWNE" "MT200350N0280W0SN150ASWSW"
#> [3] "MT200350N0280W0SN300ANWSE"
#> 
#> $geom
#> class       : SpatialPolygons 
#> features    : 3 
#> extent      : -115.3796, -115.2114, 48.76355, 48.88771  (xmin, xmax, ymin, ymax)
#> crs         : +proj=longlat +datum=WGS84 +no_defs
plot(res2$geom)
```




>     1. Missing both q and qq: nchar(string) = 21

Yes, this works.

https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/exts/CadastralSpecialServices/GetLatLon?trs=MT200350N0280W0SN320A&f=pjson

>     2. Having q and missing qq: nchar(string) = 23

This, I think, is technically invalid, or returns no results. Try this:
  
https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/exts/CadastralSpecialServices/GetLatLon?trs=MT200350N0280W0SN320ANW&f=pjson
v.s.
https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/exts/CadastralSpecialServices/GetLatLon?trs=MT200350N0280W0SN320ANWNW&f=pjson

There may be a special way to specify this because of order -- the smaller subdivision (qq) comes before (q). I think it is probably ambiguous with only one. Which does it refer to, once in the formatted string, with no delimiter or identifier?

Currently in the loop there is this code:

```r
# replace NA -> '' IN Q and QQ sections
p.q <- ifelse(is.na(p$q[i]), '', p$q[i])
p.qq <- ifelse(is.na(p$qq[i]), '', p$qq[i])
```

which is fine -- but I don't think the decision to replace `NA` that way (with `""`) was based on the API specs per se. Can confirm that NA will not work either. Or any other placeholders I could think of.

>     3. Having qq and missing q: should return an error or result for missing qq as well with a warning.

See above -- qq and q are optional, but must come together in order qq, q -- I think. User gets warnings if it does not match expected (i.e. one not both of qq and q) or if they get NA result.

>     4. Having both q and qq: nchar(string) = 25

Yep this seems to be the maximum 

>     5. If I read it correctly, when the type is PB, the 'A' is dropped, probably making the string shorter.

Yes, good catch. 

>     6. Are all the meridian codes of the same length?
  
I think they are all length `2` per http://nationalcad.blogspot.com/2015/03/plss-cadnsdi-plss-townships.html

`PRINMERCD | String | 2 | Principal meridian code from the BLM   PM Code list`

>     7. will the website take even shorter strings? Like, just the township, and return all the points in this 6X6 miles square? I've tried to find the documentation for this service on the website but got lost.

Yes, it the API will return all of the geometries in a larger area like township. But we are just grabbing the "lat" and "lon" centroids of the grid at whatever level

This works:
```r
res <- PLSS2LL(data.frame(id = 1, plssid = "MT200350N0280W0"))
```
https://gis.blm.gov/arcgis/rest/services/Cadastral/BLM_Natl_PLSS_CadNSDI/MapServer/exts/CadastralSpecialServices/GetLatLon?trs=MT200350N0280W0&f=pjson

**Comment by dylanbeaudette** [comment]
Thanks @brownag and @trilnick for the suggestions, testing, and code improvements. Merging and then will test with some local examples before pushing pkg to CRAN.

**Pull request merged**
